import { MainLayout } from '../components/layouts/MainLayout'
import Link from '../node_modules/next/link'

export default function Homepage() {
  return (
    
    <MainLayout>
      <h1>Home Page</h1>
        <h1 className={'title'}>
          Ir a <Link href="/about">About</Link>
        </h1>
        <h1 className={'title'}>
          Ir a <Link href="/contact">Contact</Link>
        </h1>
        <p className='description'>
          Get started by editing{' '} 
          <code className={'code'}>pages/index.js</code>
        </p>
    </MainLayout>
  )
}
// export default function Homepage() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <NavBar/>

//       <main className={styles.main}>
//         <h1>Home Page</h1>
//         <h1 className={styles.title}>
//           Ir a <Link href="/about">About</Link>
//         </h1>
//         <h1 className={styles.title}>
//           Ir a <Link href="/contact">Contact</Link>
//         </h1>
//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

        
//       </main>

      
//     </div>
//   )
// }
